### ISSUE TITLE
What to do next？

### ISSUE THREAD

**Issue by mkh321** [patrikhuber/fg2018-competition#10]
I want to know what to do after getting the distance file?

**Comment by patrikhuber** [comment]
The distance file is your result. If you've followed the same protocol, you can compare the numbers to our results and the results from other papers. See also #4 and #3, which might help.

**Comment by mkh321** [comment]
can you share the code for drawing&nbsp;the CED curves&nbsp;?

**Comment by patrikhuber** [comment]
I'm afraid it's been a while since I've used that code. Could you not use any standard function to plot the CDF (from numpy/scipy etc.)?

**Comment by mkh321** [comment]
Because the graph I drew is very different from the results in other people's papers, I think it is the problem of my code, so I want to try it with your code, I hope you can share your code, thank you!




---Original---
From: "Patrik ***@***.***&gt;
Date: Sun, Jul 10, 2022 00:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [patrikhuber/fg2018-competition] What to do next？ (Issue #10)




 
I'm afraid it's been a while since I've used that code. Could you not use any standard function to plot the CDF (from numpy/scipy etc.)?

**Comment by patrikhuber** [comment]
How is it very different - are your numbers much better, much worse, or does the graph look very different (i.e. not like a CDF)? I think you should get somewhere by analysing/interpreting your graph and your actual numbers.

**Comment by mkh321** [comment]
My numerical results are worse. I put the error results of each image into a list, and then use the numpy library to evaluate the mean, median, etc. I want to know how do you do it?




---Original---
From: "Patrik ***@***.***&gt;
Date: Sun, Jul 10, 2022 15:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [patrikhuber/fg2018-competition] What to do next？ (Issue #10)




 
How is it very different - are your numbers much better, much worse, or does the graph look very different (i.e. not like a CDF)? I think you should get somewhere by analysing/interpreting your graph and your actual numbers.

**Comment by Nibenitez** [comment]
Hi,
I also would like to confirm what to do after getting the distances files of each predicted mesh with the GT. I read https://github.com/patrikhuber/fg2018-competition/issues/3, but I am getting confuse on how to calculate the NME. 

Normalized Mean Error (NME) is a common metric used in evaluating the accuracy of facial landmark detection or face reconstruction algorithms. It measures the average distance between the predicted facial landmarks and the ground truth landmarks, normalized by a factor such as the interocular distance. NME is often used to assess the performance of 3D face reconstruction algorithms as well.

I investigated and to calculate the 3D NME in face reconstruction:

Calculate Euclidean Distances: Compute the Euclidean distance between each pair of corresponding ground truth and predicted landmarks for each face. I believe this is in the: [compute_vertices_to_mesh_distances.p](https://github.com/patrikhuber/fg2018-competition/blob/master/compute_vertices_to_mesh_distances.py)

Normalize by Interocular Distance: To normalize the errors and make the metric scale-independent, divide each calculated Euclidean distance by a factor such as the interocular distance. The interocular distance is typically the Euclidean distance between the two outer eye corners. This normalization helps make the metric comparable across different face sizes. And this is also calculated in the compute vertices file?

Calculate NME: After normalizing the errors, calculate the normalized mean error by averaging the normalized distances for all landmarks across all faces. The formula for NME is:

NME = (1 / N) * Σ(normalized_distance_i)
Where:

N is the total number of landmarks across all faces.
normalized_distance_i is the normalized distance for the i-th landmark.

1- So, should I sum all the distances per vertices in the file per each mesh, calculate an average and apply formula above? N=7 landamarks used?
2- Another question: Is it possible build a heat map of the error reconstruction?

I would appreciate any help as I am confused
