### ISSUE TITLE
leadboard

### ISSUE THREAD

**Issue by jylovec** [patrikhuber/fg2018-competition#13]
Where can we see the leadboard？Thanks

**Comment by patrikhuber** [comment]
Hi @jylovec,

We don't maintain a leaderboard. The best way to track people using our challenge is by looking at the papers that cite our original paper. This Google Scholar link should work: https://scholar.google.com/scholar?q=Evaluation+of+Dense+3D+Reconstruction+from+2D+Face+Images+in+the+Wild.
