### ISSUE TITLE
Website for downloading ground truth obj can not be opened.

### ISSUE THREAD

**Issue by sysuKaiYang** [patrikhuber/fg2018-competition#6]
https://facer2vm.org/fg2018/

**Comment by patrikhuber** [comment]
Hi @FengZhenhua, do you know what happened to the facer2vm website?

**Comment by FengZhenhua** [comment]
Hi Patrik,

I have no idea about the website. Will double check this with the manager.

Best wishes,

Zhenhua

**Comment by sysuKaiYang** [comment]
Hi @FengZhenhua , is everything OK?

**Comment by FengZhenhua** [comment]
> Hi @FengZhenhua , is everything OK?

I think the manager is working on it. But I have not heard any update yet.

**Comment by yjhong89** [comment]
Dear representatives, 

I cannot access to facer2vm website.

https://facer2vm.org/fg2018/
![image](https://user-images.githubusercontent.com/26890721/135371075-3d407383-285b-4912-9069-054d27110852.png)

Is there any other links to download datasets?

Thank you.

**Comment by patrikhuber** [comment]
Hi @yjhong89,

It looks like the main website (facer2vm.org) is still down. I am afraid this is out of my hands. Could you please contact CVSSP to ask them for assistance? Their contact details are here: https://www.surrey.ac.uk/centre-vision-speech-signal-processing/contact.

Thank you!

**Comment by patrikhuber** [comment]
Hi @yjhong89, @sysuKaiYang, @caozhenxiang-kouji,

The facer2vm website is now back online, and the FG2018 information is back online too with a slightly changed URL: https://facer2vm.org/px.php?dst=/fg2018.html

I'll update the URL in the readme.

**Comment by patrikhuber** [comment]
The URL is now slightly simplified and it's: https://facer2vm.org/fg2018.html.
