### ISSUE TITLE
How decide 7 points for rigid alignment?

### ISSUE THREAD

**Issue by yjhong89** [patrikhuber/fg2018-competition#7]
Hi. 

I am YJ Hong and thank you for your work.

I am running on evaluating FG2018 dataset against DECA's obj result and 
wonder how 7 landmark indices are decided in https://github.com/patrikhuber/fg2018-competition/issues/4. 

If those indices depend on .obj files I created, may I ask you how decide 7 landmakr indices? Current evaluation result is very poor even though I used pretrained DECA weights.

By the way, have you ever seen below warning while loading mesh obj file ?
![image](https://user-images.githubusercontent.com/26890721/136001589-5c869b82-33be-4cfe-b4e2-e881e3c4ae9c.png)
I think this might be a problem but I can't find out where the error source is.

Thank you!

**Comment by patrikhuber** [comment]
Hi,

Sorry for the slightly late reply - better late than never, I guess!

Those 7 landmark coordinates are given on the ground truth scans, see the `.lnd` files in this repository. You need to get the corresponding points on whatever face model / output obj's you create. In our case, we evaluated with the Surrey Face Model, which has a consistent topology. You can see in the file in https://github.com/patrikhuber/fg2018-competition/issues/4, we select the vertex indices in the SFM that correspond to these 7 landmarks. You need to do the appropriate / equivalent thing for your face model, if you use a different one.

The triangle/quads warning that you get is probably from pymesh, and it's doing exactly what it says: It seems you loaded a mesh with mixed triangles and quads, and the face order is not preserved. This should not matter for this evaluation, as this should not impact the vertex order.

Did you manage to complete the evaluation?

Best wishes,
Patrik
